version: "3"
services:
  unbound:
    image: "mvance/unbound:1.17.0"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      nginx-network:
        ipv4_address: 10.100.0.2

  wg-easy:
    depends_on: [unbound, amnesia-dns]
    environment:
      - WG_HOST=78.153.139.117
      - PASSWORD=Zoom130699
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.10.x
      - WG_DEFAULT_DNS=10.100.0.3
      - WG_ALLOWED_IPS=10.100.0.0/24, 0.0.0.0/0, ::/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_MTU=1280
    #Можно заменить на обычный WG-EASY по желанию. В моей версии немного сыровато работает добавление конфигов, но зато есть возможность объединять несколько подсетей в одну
    #Чтобы поменять на WG-EASY нужно закомментить строку ниже и расскоментить строку с IMAGE.
    build: ./wg-russian-source
    # image: ghcr.io/wg-easy/wg-easy
    network_mode: "host"
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 10.100.0.2
      - 10.100.0.3
      - 10.100.0.4

  amnesia-dns:
    depends_on: [unbound]
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
    networks:
      nginx-network:
        ipv4_address: 10.100.0.3

  ng-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
    volumes:
      - ./ng-proxy-manager/data:/data
      - ./ng-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      nginx-network:
        ipv4_address: 10.100.0.4

networks:
  nginx-network:
    external: true